live_config_reload = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#f9f5d7"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#111111"
foreground = "#f9f5d7"

[cursor]
style = "Underline"
unfocused_hollow = false

[debug]
log_level = "Warn"
persistent_logging = false

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "Roboto Mono Nerd Font"
style = "Bold"

[font.italic]
family = "Roboto Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Roboto Mono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 0.93

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 8
y = 8
