#!/bin/sh
# Read the river, riverctl, and rivertile man pages.

# Use the super key as the primary modifier
mod="Mod4"
riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"

# Programs
riverctl map normal $mod Return  spawn alacritty
riverctl map normal $mod B       spawn librewolf
riverctl map normal $mod+Shift B spawn "google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland"
riverctl map normal $mod E       spawn pcmanfm
riverctl map normal $mod S       spawn "slack --enable-features=WebRTCPipeWireCapturer"
riverctl map normal $mod D       spawn "discord --ignore-gpu-blocklist --enable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy --ozone-platform=wayland "

# Open rofi
riverctl map normal $mod space spawn "rofi -show run"

# Lock screen
riverctl map normal $mod F12 spawn "swaylock -i ~/wallpapers/wall.jpg"

# Reload river configuration
riverctl map normal $mod+Control R spawn "~/.config/river/init"

# Close the focused window
riverctl map normal $mod C close

# Exit river
riverctl map normal $mod+Shift Q exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+{left,down,up,right} to resize views
riverctl map normal $mod+Shift left resize horizontal -100
riverctl map normal $mod+Shift down resize vertical 100
riverctl map normal $mod+Shift up resize vertical -100
riverctl map normal $mod+Shift right resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# Toggle between monitors
riverctl map normal $mod+Control J focus-output next
riverctl map normal $mod+Control K focus-output previous

riverctl map normal $mod O send-to-output next

# Tags/Workspaces
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus the corresponding tag
    riverctl map normal $mod $i set-focused-tags $tags

    # Mod+Shift+[1-9] to move a window to the corresponding tag
    riverctl map normal $mod+Shift $i set-view-tags $tags
done

# Toggle float
riverctl map normal $mod+Control space toggle-float

# Toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+Shift+Control+{H,J,K,L} to change layout orientation
riverctl map normal $mod+Shift+Control K send-layout-cmd rivertile "main-location top"
riverctl map normal $mod+Shift+Control L send-layout-cmd rivertile "main-location right"
riverctl map normal $mod+Shift+Control J send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod+Shift+Control H send-layout-cmd rivertile "main-location left"

for mode in normal locked
do
    # Control volume with wpctl from wireplumber
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

    # Control MPRIS aware media players with playerctl
    # FIXME mpDris2 binding for MPD: https://github.com/eonpatapon/mpDris2
    # riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    # riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    # riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    # riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control MPD
    riverctl map $mode None XF86AudioMedia spawn 'mpc toggle'
    riverctl map $mode None XF86AudioPlay  spawn 'mpc toggle'
    riverctl map $mode None XF86AudioPrev  spawn 'mpc prev'
    riverctl map $mode None XF86AudioNext  spawn 'mpc next'

    # Control screen backlight brightness with brightnessctl
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set 5%+'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

    # Screenshot using grim
    riverctl map $mode None Print spawn "grim ~/screenshot-`date | awk '{print$4}'`.png"
done

# Set background and border color
riverctl border-color-focused 0xfe8019
riverctl border-color-unfocused 0x1d2021

# Set repeat rate
riverctl set-repeat 100 300

riverctl focus-follows-cursor normal
riverctl xcursor-theme capitaine-cursors

bash $HOME/.config/river/process.sh
